# Docker-compose file format verison, 需要与你的docker engine版本相匹配.
# Doc: https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.9" 

# 服务，主要用来整合容器，表明他们之前的关系
services:
  # 二级标签是 web，用户自定义名称，它就是服务名称
  web:
    # 基于一份Dockerfile，在使用 up 启动之时执行构建任务，
    # 这个构建标签就是 build，它可以指定 Dockerfile 所在文件夹的路径
    # 这里就是找当前文件夹
    build: .
    # 容器的依赖、启动先后的问题，先启动依赖
    # depends_on: redis
    # 端口映射
    ports:
      - "5000:5000"
    # 文件挂载
    volumes:
      - .:/code
    # 容器使用的环境变量
    environment:
      FLASK_ENV: development
  # 另外一个服务
  redis:
    image: "redis:alpine"